### ISSUE TITLE
Building llvm fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by ocadaruma** [bugvm/bugvm#49]
I tried to build bugvm/llvm but results with errors.

``` bash
$ /path/to/bugvm/llvm/build.sh
...
/path/to/bugvm/llvm/target.llvm/build/linux-x86_64/extllvm-prefix/src/extllvm/include/llvm/ADT/StringRef.h:343:19: error: ‘enable_if’ in namespace ‘std’ does not name a type
/path/to/bugvm/llvm/target.llvm/build/linux-x86_64/extllvm-prefix/src/extllvm/include/llvm/ADT/StringRef.h:343:28: error: expected unqualified-id before ‘<’ token
/path/to/bugvm/llvm/target.llvm/build/linux-x86_64/extllvm-prefix/src/extllvm/include/llvm/ADT/StringRef.h:354:19: error: ‘enable_if’ in namespace ‘std’ does not name a type
/path/to/bugvm/llvm/target.llvm/build/linux-x86_64/extllvm-prefix/src/extllvm/include/llvm/ADT/StringRef.h:354:28: error: expected unqualified-id before ‘<’ token
/path/to/bugvm/llvm/target.llvm/build/linux-x86_64/extllvm-prefix/src/extllvm/include/llvm/ADT/StringRef.h: In constructor ‘llvm::StringRef::StringRef()’:
...
make[5]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o] Error 1
make[4]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [extllvm-prefix/src/extllvm-stamp/extllvm-build] Error 2
make[1]: *** [CMakeFiles/extllvm.dir/all] Error 2
make: *** [all] Error 2
linux-x86_64 build failed
```
- Environment:
  - Ubuntu 14.04
  - gcc/g++ 4.7.3
  - cmake: 2.8.12.2

I found that adding `-std=c++11` flag fixes the problem, but I'm not sure if this is correct.

`bugvm/llvm/CMakeLists.txt L:45`

``` cmake
set(C_CXX_FLAGS "${C_CXX_FLAGS} -fvisibility=hidden -fdata-sections -ffunction-sections -std=c++11")
```

**Comment by ibinti** [comment]
BugVM was never tested on Ubuntu. It seems now good time to embrace Ubuntu because people like you actually try to use BugVM on Ubuntu.

**Comment by ibinti** [comment]
related issue https://github.com/bugvm/bugvm/issues/44

**Comment by ibinti** [comment]
The issue is not on the code but rather build tool chains configurations.

For example, successfully compiled llvm on my Ubuntu 14.04 (32-bit and 64-bit), with following  steps:
apt-get install git
apt-get install cmake
apt-get install g++
apt-get install g++-multilib
apt-get install gcc-multilib
apt-get install libcap-dev
apt-get install zlib1g-dev
apt-get install libxml2-dev
apt-get install openjdk-7-jdk

Install GNU Patch 2.7.3
Set JAVA_HOME environment

Refer: http://bugvm.com/vm-llvm-on-ubuntu-14-04/
