### ISSUE TITLE
Change Website to say what BugVM is?

### ISSUE THREAD

**Issue by fingolfin** [bugvm/bugvm#72]
The text on https://bugvm.com/ currently starts with these words:

```
We are the BugVM

BugVM is a free open source alternative to closed, commercial, and now discontinued RoboVM.
```

and so on. But what _is_ BugVM? Under "Current Status" (???) it says: "BugVM can be used to develop a native iOS app with Java." So I assume this is what BugVM is all about? From a PR point of view, it might be a good idea to start with that. Unless you intentionally want to limit your "market" to people who know this RoboVM?

I could not find a repository for the website, nor any specific hints as to how to report issues with the website, so after some searching around I ended up using this issue tracker.

**Comment by ibinti** [comment]
Good point.
I could use your help if you write up a brief introduction to BugVM by any chance.
BugVM welcomes any community contribution.

**Comment by fingolfin** [comment]
I'd help, but I actually don't know anything about BugVM -- just came across it via a HackerNews story, and thought I'd leave the feedback,

**Comment by javatlacati** [comment]
Same here :smile:

**Comment by iAlbi93** [comment]
BugVM is composed by:
- Cocoa Touch Bindings API Library: bugvm-cocoatouch.jar;
- ObjectiveC Runtime Bindings API Library: bugvm-objc.jar;
- Runtime LLVM API Library: bugvm-rt.jar;
- Compiler Library: bugvm-dist-compiler.jar;
- Native Library libbugvm-llvm.dylib for LLVM C-bingings;
- Native Library libbugvm-libmobiledevice.dylib for mobile device bindings.
  The main idea is to write Java code for the iOS platform, then a compiler takes in input .class  les from the Java compilation and compiles them into ObjectiveC native code. For this step a LLVM (Low Level Virtual Ma- chine) is needed and is in charge of resolving the bindings between Java code and native C code. BugVM is able to resolve the lack of Java support on iOS because the process of compilation of the app into native code follows the AOT (Ahead-Of-Time) principle: the Java code is compiled into native C code during the installation process of the app onto the smartphone, so at runtime no Java code is present.

(In my experience with robovm/bugvm I can say this :-) )
